import type { Position } from "@/lib/types";

export const positions: Position[] = [
  {
    id: "mur-2026-0001",
    title: "Assegno di ricerca in machine learning per modelli climatici",
    institution: "Universita di Bologna",
    department: "Dipartimento di Informatica - Scienza e Ingegneria",
    location: "Bologna",
    region: "Emilia-Romagna",
    positionType: "Assegno",
    discipline: "Computer Science",
    ssd: "INFO-01/A",
    fundingType: "PRIN",
    deadline: "2026-06-14",
    publishedAt: "2026-05-03",
    sourceName: "MUR/Cineca",
    sourceUrl: "https://bandi.mur.gov.it/",
    salaryOrAmount: "EUR 24.000 annui lordi",
    duration: "12 mesi",
    language: "IT/EN",
    summary:
      "Posizione annuale per sviluppo e validazione di modelli di machine learning applicati a dati climatici. Il progetto e indicato come finanziato PRIN e richiede competenze in Python, statistica e analisi dati.",
    requirements: ["Laurea magistrale o PhD coerente", "Python e machine learning", "Esperienza con dati scientifici"]
  },
  {
    id: "mur-2026-0002",
    title: "Contratto di ricerca su biomateriali per medicina rigenerativa",
    institution: "Politecnico di Milano",
    department: "Dipartimento di Chimica, Materiali e Ingegneria Chimica",
    location: "Milano",
    region: "Lombardia",
    positionType: "Contratto di ricerca",
    discipline: "Materials Science",
    ssd: "IIND-03/B",
    fundingType: "PNRR",
    deadline: "2026-05-29",
    publishedAt: "2026-05-02",
    sourceName: "MUR/Cineca",
    sourceUrl: "https://bandi.mur.gov.it/",
    salaryOrAmount: "Da bando ufficiale",
    duration: "24 mesi",
    language: "IT",
    summary:
      "Contratto biennale collegato a linea PNRR per progettazione e caratterizzazione di biomateriali. La scheda dara evidenza a durata, ente, settore e link ufficiale appena importati dal MUR.",
    requirements: ["PhD o esperienza equivalente", "Caratterizzazione materiali", "Pubblicazioni coerenti"]
  },
  {
    id: "mur-2026-0003",
    title: "Bando di dottorato in Economics and Data Science",
    institution: "Universita di Torino",
    department: "Scuola di Dottorato",
    location: "Torino",
    region: "Piemonte",
    positionType: "PhD",
    discipline: "Economics",
    ssd: "ECON-01/A",
    fundingType: "MUR",
    deadline: "2026-07-01",
    publishedAt: "2026-04-30",
    sourceName: "MUR/Cineca",
    sourceUrl: "https://bandi.mur.gov.it/",
    salaryOrAmount: "Borsa dottorale",
    duration: "36 mesi",
    language: "IT/EN",
    summary:
      "Call di dottorato con focus su economia quantitativa, data science e policy evaluation. La UX mette in primo piano deadline, posti disponibili, requisiti e documentazione richiesta.",
    requirements: ["Titolo magistrale", "Competenze quantitative", "Progetto di ricerca"]
  },
  {
    id: "mur-2026-0004",
    title: "Ricercatore tenure track in storia contemporanea",
    institution: "Universita degli Studi di Firenze",
    department: "Dipartimento SAGAS",
    location: "Firenze",
    region: "Toscana",
    positionType: "RTT",
    discipline: "Humanities",
    ssd: "HIST-03/A",
    fundingType: "MUR",
    deadline: "2026-06-03",
    publishedAt: "2026-04-28",
    sourceName: "MUR/Cineca",
    sourceUrl: "https://bandi.mur.gov.it/",
    salaryOrAmount: "Da bando ufficiale",
    duration: "Tenure track",
    language: "IT",
    summary:
      "Procedura per ricercatore tenure track nel settore storia contemporanea. La scheda normalizzata permette confronto rapido con altre procedure dello stesso GSD.",
    requirements: ["Requisiti Legge 240/2010", "Produzione scientifica coerente", "Attivita didattica"]
  },
  {
    id: "mur-2026-0005",
    title: "Procedura selettiva per professore ordinario in sistemi di elaborazione delle informazioni",
    institution: "Universita degli Studi di Padova",
    department: "Dipartimento di Ingegneria dell'Informazione",
    location: "Padova",
    region: "Veneto",
    positionType: "Professore I fascia",
    discipline: "Computer Science",
    ssd: "INFO-01/A",
    fundingType: "MUR",
    deadline: "2026-06-21",
    publishedAt: "2026-05-04",
    sourceName: "MUR/Cineca",
    sourceUrl: "https://bandi.mur.gov.it/",
    salaryOrAmount: "Trattamento economico da professore ordinario",
    duration: "Tempo indeterminato",
    language: "IT",
    summary:
      "Procedura per professore di prima fascia con profilo in sistemi di elaborazione delle informazioni, attivita di ricerca su AI affidabile, sistemi distribuiti e didattica nei corsi magistrali.",
    requirements: ["Abilitazione scientifica nazionale I fascia", "Produzione scientifica internazionale", "Esperienza didattica e coordinamento ricerca"]
  },
  {
    id: "mur-2026-0006",
    title: "Chiamata per professore associato in economia applicata",
    institution: "Universita Ca' Foscari Venezia",
    department: "Dipartimento di Economia",
    location: "Venezia",
    region: "Veneto",
    positionType: "Professore II fascia",
    discipline: "Economics",
    ssd: "ECON-02/A",
    fundingType: "MUR",
    deadline: "2026-06-10",
    publishedAt: "2026-05-01",
    sourceName: "MUR/Cineca",
    sourceUrl: "https://bandi.mur.gov.it/",
    salaryOrAmount: "Trattamento economico da professore associato",
    duration: "Tempo indeterminato",
    language: "IT/EN",
    summary:
      "Chiamata per seconda fascia in economia applicata, con attenzione a valutazione delle politiche pubbliche, metodi quantitativi e didattica internazionale.",
    requirements: ["Abilitazione scientifica nazionale II fascia", "Pubblicazioni coerenti con il settore", "Capacita didattica in italiano e inglese"]
  },
  {
    id: "mur-2026-0007",
    title: "Procedura per professore associato in archeologia classica",
    institution: "Sapienza Universita di Roma",
    department: "Dipartimento di Scienze dell'Antichita",
    location: "Roma",
    region: "Lazio",
    positionType: "Professore II fascia",
    discipline: "Humanities",
    ssd: "ARCH-01/D",
    fundingType: "MUR",
    deadline: "2026-05-31",
    publishedAt: "2026-04-29",
    sourceName: "MUR/Cineca",
    sourceUrl: "https://bandi.mur.gov.it/",
    salaryOrAmount: "Trattamento economico da professore associato",
    duration: "Tempo indeterminato",
    language: "IT",
    summary:
      "Procedura di seconda fascia per archeologia classica, con profilo orientato a ricerca sul Mediterraneo antico, scavo, valorizzazione del patrimonio e didattica di base.",
    requirements: ["ASN II fascia", "Esperienza di ricerca sul campo", "Attivita didattica universitaria"]
  },
  {
    id: "mur-2026-0008",
    title: "Professore straordinario a tempo determinato in medicina traslazionale",
    institution: "Humanitas University",
    department: "Department of Biomedical Sciences",
    location: "Pieve Emanuele",
    region: "Lombardia",
    positionType: "Professore straordinario",
    discipline: "Life Sciences",
    ssd: "BIOS-07/A",
    fundingType: "PNRR",
    deadline: "2026-06-27",
    publishedAt: "2026-05-02",
    sourceName: "MUR/Cineca",
    sourceUrl: "https://bandi.mur.gov.it/",
    salaryOrAmount: "Da bando ufficiale",
    duration: "36 mesi",
    language: "IT/EN",
    summary:
      "Posizione senior a tempo determinato collegata a linea PNRR in medicina traslazionale, con responsabilita di ricerca, didattica avanzata e coordinamento di unita progettuali.",
    requirements: ["Profilo scientifico senior", "Leadership di progetti competitivi", "Esperienza didattica e clinico-traslazionale"]
  }
];

export function getPositionById(id: string) {
  return positions.find((position) => position.id === id);
}
